<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../../src/Common/Common.csproj" />
  </ItemGroup>
  <Target Name="CopyToPluginArtifacts" AfterTargets="Build">
    <PropertyGroup>
      <PluginOutputDir>$(MSBuildThisFileDirectory)../../artifacts/plugins/</PluginOutputDir>
    </PropertyGroup>
    <MakeDir Directories="$(PluginOutputDir)" />
    <ItemGroup>
      <PluginArtifacts Include="$(OutputPath)*.dll" />
    </ItemGroup>
    <Copy SourceFiles="@(PluginArtifacts)" DestinationFolder="$(PluginOutputDir)" SkipUnchangedFiles="true" />
  </Target>
</Project>
