<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="../Common/Common.csproj" />
    <ProjectReference Include="../../plugins/Storage.Checksum/Storage.Checksum.csproj" ReferenceOutputAssembly="false" PrivateAssets="all" />
    <ProjectReference Include="../../plugins/Friend.LegacyBase64/Friend.LegacyBase64.csproj" ReferenceOutputAssembly="false" PrivateAssets="all" />
    <ProjectReference Include="../../plugins/Adapter.LegacyBase64/Adapter.LegacyBase64.csproj" ReferenceOutputAssembly="false" PrivateAssets="all" />
  </ItemGroup>
</Project>
