<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="Plugins/**" />
    <EmbeddedResource Remove="Plugins/**" />
    <None Remove="Plugins/**" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="../Shared/Common.csproj" />
    <ProjectReference Include="../Lab5/Plugins/Storage.Checksum/Storage.Checksum.csproj" ReferenceOutputAssembly="false" PrivateAssets="all" />
    <ProjectReference Include="Plugins/Friend.LegacyBase64/Friend.LegacyBase64.csproj" ReferenceOutputAssembly="false" PrivateAssets="all" />
    <ProjectReference Include="Plugins/Adapter.LegacyBase64/Adapter.LegacyBase64.csproj" ReferenceOutputAssembly="false" PrivateAssets="all" />
  </ItemGroup>
</Project>
